name = "aredl-coordinator"
main = "build/worker/shim.mjs"
compatibility_date = "2025-10-11"

[build]
command = "worker-build --release"

[vars]
FRONTEND_ORIGIN = "https://cameron-b63.github.io"
FRONTEND_BASE_PATH = "/AREDL_Coordinator"
AREDL_API_BASE = "https://api.aredl.net/v2/api"
AREDL_CLAN_ID = "66fe1773-8ece-4f1e-a252-65786ae11f02"
DISCORD_GUILD_ID = "1197386547796918277"
DISCORD_REQUIRED_ROLE_ID = "1382421122754023434"

[[d1_databases]]
binding = "DB"
database_name = "aredl-coordinator"
database_id = "8b090da8-1325-408a-826a-8aa7171cd800"
migrations_dir = "migrations"
